"""Initial migration

Revision ID: 52ee2890ee8e
Revises: 
Create Date: 2023-11-17 13:14:01.153501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52ee2890ee8e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('AccessToken', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('FirstName', sa.String(length=20), nullable=False),
    sa.Column('LastName', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=60), nullable=False),
    sa.Column('notification', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('AccessToken'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('date_posted', sa.DateTime(), nullable=False),
    sa.Column('Description', sa.String(length=100), nullable=False),
    sa.Column('AssignedTo', sa.String(length=20), nullable=False),
    sa.Column('Createdby', sa.Integer(), nullable=False),
    sa.Column('Status', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['Createdby'], ['user.AccessToken'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post')
    op.drop_table('user')
    # ### end Alembic commands ###
