"""Update User Model

Revision ID: 777ed196c527
Revises: 52ee2890ee8e
Create Date: 2023-11-17 15:04:06.745741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '777ed196c527'
down_revision = '52ee2890ee8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
